"""Сид моделей для всех брендов (вне миграции 0004 — Audi)

Inlined из brands/models/*.json. Всего ~3400 моделей по 126 брендам.
ON CONFLICT (brand_id, name) DO NOTHING — идемпотентно, 77 моделей Audi
из миграции 0004 будут пропущены без ошибки.

Revision ID: 0005_seed_all_vehicle_models
Revises: 0004_seed_audi_models
Create Date: 2026-05-17
"""
from alembic import op
from sqlalchemy import text


revision = "0005_seed_all_vehicle_models"
down_revision = "0004_seed_audi_models"
branch_labels = None
depends_on = None


MODELS_BY_BRAND: dict[str, list[str]] = {'AC': ['Cobra'],
 'AITO': ['M5', 'M7', 'M8', 'M9'],
 'Acura': ['ADX',
           'CDX',
           'CL',
           'EL',
           'ILX',
           'Integra',
           'Legend',
           'MDX',
           'NSX',
           'RDX',
           'RL',
           'RLX',
           'RSX',
           'SLX',
           'TL',
           'TLX',
           'TSX',
           'Vigor',
           'ZDX'],
 'Alfa Romeo': ['145',
                '146',
                '147',
                '155',
                '156',
                '159',
                '164',
                '166',
                '33',
                '33 Stradale',
                '4C',
                '75',
                '8C',
                '90',
                'Brera',
                'Giulia',
                'Giulietta',
                'GT',
                'GTV',
                'Junior',
                'MiTo',
                'Milano',
                'Spider',
                'Stelvio',
                'Tonale'],
 'Alpina': ['B10',
            'B11',
            'B12',
            'B3',
            'B4',
            'B5',
            'B6',
            'B7',
            'B8',
            'B9',
            'C1',
            'C2',
            'D10',
            'D3',
            'D4',
            'D5',
            'Roadster',
            'XB7',
            'XD3',
            'XD4'],
 'Alpine': ['A110', 'A290'],
 'Aston Martin': ['AR1',
                  'Cygnet',
                  'DB11',
                  'DB12',
                  'DB5',
                  'DB7',
                  'DB9',
                  'DBS',
                  'DBX',
                  'Lagonda',
                  'One-77',
                  'Rapide',
                  'Tickford Capri',
                  'Vanquish',
                  'Vantage',
                  'Virage',
                  'Zagato'],
 'Audi': ['50',
          '80',
          '90',
          '100',
          '200',
          'A1',
          'A2',
          'A3',
          'A4',
          'A4 allroad quattro',
          'A5',
          'A5L',
          'A6',
          'A6 allroad quattro',
          'A6 e-tron',
          'A7',
          'A8',
          'Cabriolet',
          'Coupe',
          'e-tron',
          'e-tron GT',
          'e-tron S',
          'e-tron Sportback',
          'e-tron Sportback S',
          'E5 Sportback',
          'E7X',
          'Q2',
          'Q2 e-tron',
          'Q3',
          'Q3 Sportback',
          'Q4 e-tron',
          'Q4 Sportback e-tron',
          'Q5',
          'Q5 e-tron',
          'Q5 Sportback',
          'Q6',
          'Q6 e-tron',
          'Q6 e-tron Sportback',
          'Q7',
          'Q8',
          'Q8 e-tron',
          'Q8 Sportback e-tron',
          'Quattro',
          'Quattro Sport',
          'R8',
          'RS e-tron GT',
          'RS Q3',
          'RS Q3 Sportback',
          'RS Q8',
          'RS2',
          'RS3',
          'RS4',
          'RS5',
          'RS6',
          'RS7',
          'S1',
          'S2',
          'S3',
          'S4',
          'S5',
          'S6',
          'S6 e-tron',
          'S7',
          'S8',
          'SQ2',
          'SQ5',
          'SQ5 Sportback',
          'SQ6 e-tron',
          'SQ6 e-tron Sportback',
          'SQ7',
          'SQ8',
          'SQ8 e-tron',
          'SQ8 Sportback e-tron',
          'TT',
          'TT RS',
          'TTS',
          'V8'],
 'Aurus': ['Арсенал', 'Комендант', 'Сенат'],
 'Avatr': ['06', '07', '11', '12'],
 'BAIC': ['EX3',
          'BJ30',
          'BJ40',
          'BJ60',
          'BJ80',
          'BJ90',
          'EU5 Plus',
          'EU7',
          'Rubics Cube',
          'X3',
          'X5',
          'X7',
          'BJ40 Plus',
          'BJ41',
          'BJ60 Thunder',
          'BJ81',
          'BJEV EX5',
          'EU5',
          'EU8',
          'Huansu S6',
          'Jeep 2500',
          'Ruixiang X3',
          'Ruixiang X5',
          'Senova E-Series',
          'Senova X55',
          'Senova Zhixing',
          'U5',
          'U5 Plus',
          'U7',
          'X35',
          'X55',
          'X75'],
 'BAW': ['Yusheng 007', 'Ace M7', 'BJ 212', 'Calorie', 'Leichi', 'Luba', 'MPV'],
 'BMW': ['02 (E10)',
         '1-Series',
         '1M',
         '2-Series',
         '2-Series Active Tourer',
         '2-Series Gran Tourer',
         '3-Series',
         '3-Series Gran Turismo',
         '321',
         '326',
         '340',
         '4-Series',
         '5-Series',
         '5-Series Gran Turismo',
         '503',
         '6-Series',
         '6-Series Gran Turismo',
         '600',
         '7-Series',
         '8-Series',
         'E3',
         'E9',
         'i3',
         'i4',
         'i5',
         'i7',
         'i8',
         'Isetta',
         'iX',
         'iX1',
         'iX2',
         'iX3',
         'M1',
         'M2',
         'M3',
         'M4',
         'M5',
         'M6',
         'M8',
         'Neue Klasse',
         'X1',
         'X2',
         'X3',
         'X4',
         'X5',
         'X6',
         'X7',
         'XM',
         'Z1',
         'Z3',
         'Z4',
         'Z8'],
 'BYD': ['D1',
         'Datang',
         'Destroyer 05',
         'Dolphin',
         'e1',
         'e2',
         'e3',
         'e5',
         'e6',
         'e7',
         'e9',
         'F0',
         'F3',
         'F5',
         'F6',
         'F7',
         'FangChengBao Leopard 5',
         'FangChengBao Leopard 8',
         'FangChengBao Titanium 3',
         'FangChengBao Titanium 7',
         'Flyer',
         'Frigate 07',
         'G3',
         'G6',
         'Han',
         'Han L',
         'L3',
         'Linghui e5',
         'Linghui e7',
         'Linghui e9',
         'Linghui M9',
         'M6',
         'Qin',
         'Qin L DM',
         'Qin L EV',
         'Qin Max',
         'Qin Plus',
         'Qin Pro',
         'S6',
         'S7',
         'Sea Lion 05 DM',
         'Sea Lion 05 EV',
         'Sea Lion 06',
         'Sea Lion 07 EV',
         'Sea Lion 07 DM',
         'Sea Lion 08',
         'Seagull',
         'Seal',
         'Seal 06 DM',
         'Seal 06 EV',
         'Seal 06 GT',
         'Seal 07',
         'Seal 08',
         'Seal 05',
         'Shark',
         'Song',
         'Song L EV',
         'Song L DM',
         'Song Max',
         'Song Plus',
         'Song Pro',
         'Song Ultra',
         'Tang',
         'Tang L',
         'Xia',
         'Yangwang U7',
         'Yangwang U8',
         'Yangwang U9',
         'Yuan',
         'Yuan Plus',
         'Yuan Pro',
         'Yuan Up'],
 'Bajaj': ['Qute'],
 'Belgee': ['S50', 'X50', 'X50+', 'X70', 'X80'],
 'Bentley': ['Arnage',
             'Azure',
             'Bentayga',
             'Brooklands',
             'Continental',
             'Continental GT',
             'Eight',
             'Flying Spur',
             'Mulsanne',
             'R-Type',
             'S',
             'T-Series',
             'Turbo R'],
 'Bugatti': ['Chiron', 'Tourbillon', 'Veyron'],
 'Buick': ['Cascada',
           'Century',
           'Electra E5',
           'Electra E7',
           'Electra L7',
           'Enclave',
           'Encore',
           'Encore GX',
           'Envision',
           'Envision Plus',
           'Envista',
           'Excelle',
           'Excelle GT',
           'Excelle GX',
           'Excelle XT',
           'GL6',
           'GL8',
           'GL8 Avenir',
           'GL8 Century',
           'GL8 Encasa',
           'GL8 ES',
           'GL8 Firstland',
           'LaCrosse',
           'LeSabre',
           'Lucerne',
           'Park Avenue',
           'Rainier',
           'Regal',
           'Rendezvous',
           'Riviera',
           'Sail',
           'Skylark',
           'Special',
           'Terraza',
           'Velite 5',
           'Velite 6',
           'Velite 7',
           'Verano',
           'Verano GS',
           'Verano Pro'],
 'Cadillac': ['ATS',
              'BLS',
              'Brougham',
              'Catera',
              'Celestiq',
              'CT4',
              'CT5',
              'CT6',
              'CTS',
              'DeVille',
              'DTS',
              'Eldorado',
              'ELR',
              'Escalade',
              'Escalade IQ',
              'Fleetwood',
              'GT4',
              'Lyriq',
              'Optiq',
              'Seville',
              'SRX',
              'STS',
              'Vistiq',
              'XLR',
              'XT4',
              'XT5',
              'XT6',
              'XTS'],
 'Changan': ['Alsvin',
             'Alsvin V7',
             'Benben',
             'CS15',
             'CS35',
             'CS35 Max',
             'CS35 Plus',
             'CS55',
             'CS55 E-Rock',
             'CS55 Plus',
             'CS75',
             'CS75 Plus',
             'CS75 Pro',
             'CS85 Coupe',
             'CS95',
             'CS95 Plus',
             'CX20',
             'Eado',
             'Eado DT',
             'Eado Plus',
             'Eado XT',
             'Hunter',
             'Hunter Plus',
             'Kaicene F70',
             'Kaicene Ruixing M60',
             'Kaicene Star 5',
             'Lamore',
             'Lantop',
             'Linmax',
             'Lumin',
             'Qiyuan Nevo A05',
             'Qiyuan Nevo A06',
             'Qiyuan Nevo A07',
             'Qiyuan Nevo E07',
             'Qiyuan Nevo Hunter K50',
             'Qiyuan Nevo Q05',
             'Qiyuan Nevo Q06',
             'Qiyuan Nevo Q07',
             'Raeton',
             'Raeton CC',
             'Raeton Plus',
             'UNI-K',
             'UNI-S',
             'UNI-T',
             'UNI-V',
             'UNI-Z',
             'X5 Plus',
             'X7 Plus',
             'Yida'],
 'Chery': ['Bonus 3 - A19',
           'Amulet A15',
           'Arrizo 3',
           'Arrizo 5',
           'Arrizo 5 GT',
           'Arrizo 5 Plus',
           'Arrizo 5 Pro',
           'Arrizo 5e',
           'Arrizo 6 Pro',
           'Arrizo 7',
           'Arrizo 8',
           'Arrizo 8 Pro',
           'Arrizo EX',
           'Arrizo GX',
           'Arrizo M7',
           'Oriental Son',
           'Beat',
           'Bonus A13',
           'CrossEastar',
           'E5',
           'Eastar',
           'eQ1',
           'Big Ant eQ5',
           'eQ7',
           'Explore 06',
           'Fora A21',
           'Fulwin A8',
           'Fulwin A8L',
           'Fulwin A9',
           'Fulwin A9L',
           'Fulwin T10',
           'Fulwin T11',
           'Fulwin T6',
           'Fulwin T8',
           'Fulwin T8L',
           'Fulwin T9',
           'Fulwin T9L',
           'Fulwin X3',
           'Fulwin X3 Plus',
           'Fulwin X3L',
           'indiS S18D',
           'Kimo A1',
           'Little Ant',
           'M11',
           'Omoda 5',
           'QQ Sweet',
           'QQ3',
           'QQ6 S21',
           'QQ Domi',
           'QQ Ice Cream',
           'Tiggo T11',
           'Tiggo 2',
           'Tiggo 2 Pro',
           'Tiggo 3',
           'Tiggo 3x',
           'Tiggo 3xe',
           'Tiggo 4',
           'Tiggo 4 Pro',
           'Tiggo 5',
           'Tiggo 5x',
           'Tiggo 7',
           'Tiggo 7 Plus',
           'Tiggo 7 Pro',
           'Tiggo 7 Pro Max',
           'Tiggo 7 Pro Plug-In-Hybrid',
           'Tiggo 7L',
           'Tiggo 8',
           'Tiggo 8 Plus',
           'Tiggo 8 Pro',
           'Tiggo 8 Pro e+ Hybrid',
           'Tiggo 8 Pro Max',
           'Tiggo 8 Pro Plug-In-Hybrid',
           'Tiggo 8L',
           'Tiggo 9',
           'Tiggo 9X',
           'Tiggo e',
           'Very A13',
           'X1'],
 'Chevrolet': ['3600',
               'Alero',
               'Astro',
               'Avalanche',
               'Aveo',
               'Beretta',
               'Blazer',
               'Blazer EV',
               'Blazer K5',
               'Blazer S-10',
               'Bolt',
               'C10',
               'Camaro',
               'Caprice',
               'Captiva',
               'Cavalier',
               'Celebrity',
               'Cobalt',
               'Colorado',
               'Corsica',
               'Corvette',
               'Cruze',
               'Damas',
               'Epica',
               'Equinox',
               'Equinox EV',
               'Equinox Plus',
               'Evanda',
               'Groove',
               'HHR',
               'Impala',
               'Lacetti',
               'Lanos',
               'Lumina',
               'Lumina APV',
               'Malibu',
               'Menlo',
               'Metro',
               'Monte Carlo',
               'Monza',
               'MW',
               'Nexia',
               'Niva',
               'Nova',
               'Nubira',
               'Onix',
               'Optra',
               'Orlando',
               'Prizm',
               'Rezzo',
               'S10',
               'Seeker',
               'Silverado',
               'Sonic',
               'Spark',
               'SSR',
               'Suburban',
               'Tacuma',
               'Tahoe',
               'Tracker',
               'TrailBlazer',
               'Trans Sport',
               'Traverse',
               'Trax',
               'Uplander',
               'Van',
               'Venture',
               'Viva',
               'Volt'],
 'Chrysler': ['180',
              '200',
              '300',
              '300 Letter Series',
              '300C',
              '300M',
              'Aspen',
              'Cirrus',
              'Concorde',
              'Cordoba',
              'Crossfire',
              'Fifth Avenue',
              'Grand Voyager',
              'Imperial',
              'Intrepid',
              'Le Baron',
              'LHS',
              'Neon',
              'New Yorker',
              'Newport',
              'Pacifica',
              'Prowler',
              'PT Cruiser',
              'Saratoga',
              'Sebring',
              'Stratus',
              'Town and Country',
              'Vision',
              'Voyager',
              'Ypsilon'],
 'Citroen': ['2CV',
             'Ami',
             'Berlingo',
             'BX',
             'C-Crosser',
             'C-Elysee',
             'C-Zero',
             'C1',
             'C15',
             'C2',
             'C25',
             'C3',
             'C3-XR',
             'C3 Aircross',
             'C3 Picasso',
             'C3L',
             'C4',
             'C4 Aircross',
             'C4 Cactus',
             'C4 Picasso',
             'C4 Spacetourer',
             'C4 X',
             'C5',
             'C5 Aircross',
             'C5 X',
             'C6',
             'C8',
             'DS3',
             'DS3 Crossback',
             'DS4',
             'DS4 Cross',
             'DS5',
             'DS7',
             'DS N°8',
             'DS9',
             'E-Mehari',
             'Evasion',
             'Grand C4 Picasso',
             'Grand C4 Spacetourer',
             'GS',
             'Jumper',
             'Jumpy',
             'Nemo',
             'Saxo',
             'Spacetourer',
             'Visa',
             'Xantia',
             'XM',
             'Xsara',
             'Xsara Picasso',
             'ZX'],
 'Cupra': ['Ateca', 'Born', 'Formentor', 'Leon', 'Tavascan', 'Terramar'],
 'Dacia': ['Bigster',
           'Dacia Dokker',
           'Duster',
           'Lodgy',
           'Lodgy Stepway',
           'Logan',
           'Logan MCV',
           'Logan MCV Stepway',
           'Logan Pick-Up',
           'Sandero',
           'Sandero Stepway',
           'Spring',
           'Stiker'],
 'Daewoo': ['Alpheon',
            'Cielo',
            'Damas',
            'Espero',
            'Evanda',
            'G2X',
            'Gentra',
            'Kalos',
            'Korando',
            'Lacetti',
            'Lanos',
            'Leganza',
            'LeMans',
            'Lublin 3',
            'Magnus',
            'Matiz',
            'Nexia',
            'Nubira',
            'Prince',
            'Racer',
            'Rezzo',
            'Royale',
            'Sens',
            'Tacuma',
            'Tico',
            'Tosca',
            'Winstorm'],
 'Daihatsu': ['Altis',
              'Applause',
              'Atrai',
              'Atrai7',
              'Be-Go',
              'Boon',
              'Boon Luminas',
              'Hijet Caddie',
              'Cast',
              'Charade',
              'Charade Social',
              'Charmant',
              'Coo',
              'Copen',
              'Cuore',
              'Delta',
              'Esse',
              'Gran Max',
              'Hijet',
              'Leeza',
              'Materia',
              'Max',
              'Mebius',
              'Midget II',
              'Mira',
              'Mira Avy',
              'Mira Cocoa',
              'Mira e:S',
              'Mira Gino',
              'Mira Gino 1000',
              'Mira Moderno',
              'Mira Tocot',
              'Move',
              'Move Canbus',
              'Move Conte',
              'Move Latte',
              'Naked',
              'Opti',
              'Pyzar',
              'Rocky',
              'Rugger',
              'Sirion',
              'Sonica',
              'Storia',
              'Taft',
              'Tanto',
              'Tanto Exe',
              'Terios',
              'Terios Kid',
              'Terios Lucia',
              'Thor',
              'Wake',
              'Xenia',
              'YRV'],
 'Datsun': ['Cross', 'Go', 'mi-Do', 'on-DO'],
 'DeLorean': ['DMC-12'],
 'Dodge': ['Aries',
           'Avenger',
           'Caliber',
           'Caravan',
           'Challenger',
           'Charger',
           'Dakota',
           'Dart',
           'Durango',
           'Dynasty',
           'Grand Caravan',
           'Hornet',
           'Intrepid',
           'JCUV',
           'Journey',
           'Magnum',
           'Mirada',
           'Neon',
           'Nitro',
           'Omni',
           'Raider',
           'Ram',
           'Ramcharger',
           'Shadow',
           'Spirit',
           'Stealth',
           'Stratus',
           'Viper'],
 'Dongfeng': ['580',
              'A9',
              'Aeolus A30',
              'Aeolus A60',
              'Aeolus AX3',
              'Aeolus AX4',
              'Aeolus AX5',
              'Aeolus AX7',
              'Aeolus AX7 Plus',
              'Aeolus AX7 Pro',
              'Aeolus E70',
              'Aeolus Haohan',
              'Aeolus Huge',
              'Aeolus Yixuan',
              'Aeolus Yixuan GS',
              'Aeolus Yixuan Max',
              'AX4',
              'AX7',
              'C-Series',
              'DF6',
              'E11K',
              'EC36',
              'EP 007',
              'EP 008',
              'Nano EX1',
              'Fengon 370',
              'DFSK Fengon 500',
              'Fengon 580',
              'Fengon 580 Pro',
              'Fengon e3',
              'DFSK Fengon ix5',
              'DFSK Fengon ix7',
              'Fengon Mini EV',
              'Fengon S560',
              'H30 Cross',
              'Huge',
              'K33-561',
              'Landian E5',
              'Landian E5 Plus',
              'Mage',
              'Mengshi MS600',
              'MPV',
              'Nammi 01',
              'Nammi 06',
              'Oting',
              'Rich',
              'Rich 6',
              'Rich 7',
              'S30',
              'Shine GS',
              'Shine Max',
              'Aeolus Sky EV01',
              'Z9'],
 'EXEED': ['ET5',
           'EX7',
           'Exlantix ES',
           'Exlantix ET',
           'LX',
           'RX',
           'Sterra ES',
           'Sterra ET',
           'TX',
           'TXL',
           'VX',
           'Yaoguang'],
 'Evolute': ['i-Jet', 'i-Joy', 'i-Pro', 'i-Sky', 'i-Space', 'i-Van'],
 'FAW': ['6350',
         '6371',
         'Bestune B70',
         'Bestune B70S',
         'Bestune E01',
         'Bestune M9',
         'Bestune NAT',
         'Bestune Pony',
         'Bestune T33',
         'Bestune T55',
         'Bestune T77',
         'Bestune T90',
         'Bestune T99',
         'Bestune Yueyi 07',
         'Besturn B30',
         'Besturn B50',
         'Besturn B70',
         'Besturn X40',
         'Besturn X40 EV',
         'Besturn X80',
         'Jinn',
         'Junpai D60',
         'Landmark',
         'Oley',
         'Senia R7',
         'Senia R9',
         'V2',
         'V5',
         'Vita'],
 'Ferrari': ['12Cilindri',
             '296 GTB',
             '296 GTS',
             '328',
             '348',
             '360',
             '458 Italia',
             '458 Speciale',
             '458 Spider',
             '488 GTB',
             '488 Pista',
             '488 Spider',
             '575M Maranello',
             '599 GTB Fiorano',
             '599 GTO',
             '612 Scaglietti',
             '812 GTS',
             '812 Superfast',
             '849 Testarossa',
             'Amalfi',
             'California',
             'Daytona SP3',
             'Enzo Ferrari',
             'F12 Berlinetta',
             'F12 TDF',
             'F355',
             'F40',
             'F430',
             'F50',
             'F80',
             'F8 Spider',
             'F8 Tributo',
             'FF',
             'GTC4Lusso',
             'LaFerrari',
             'Monza SP',
             'Portofino',
             'Purosangue',
             'Roma',
             'SF90 Stradale',
             'Testarossa'],
 'Fiat': ['124',
          '124 Spider',
          '125',
          '128',
          '500',
          '500X',
          'Albea',
          'Brava',
          'Bravo',
          'Coupe',
          'Croma',
          'Doblo',
          'Freemont',
          'Fullback',
          'Grande Punto',
          'Linea',
          'Multipla',
          'Palio',
          'Panda',
          'Punto',
          'Qubo',
          'Regata',
          'Ritmo',
          'Scudo',
          'Sedici',
          'Seicento',
          'Stilo',
          'Strada',
          'Talento',
          'Tipo',
          'Ulysse',
          'Uno'],
 'Fisker': ['Karma', 'Ocean'],
 'Ford': ['Aerostar',
          'Aspire',
          'B-MAX',
          'Bronco',
          'Bronco II',
          'Bronco Sport',
          'C-MAX',
          'Capri',
          'Contour',
          'Cougar',
          'Crown Victoria',
          'Econovan',
          'EcoSport',
          'Edge',
          'Eifel',
          'Equator',
          'Equator Sport',
          'Escape',
          'Escort',
          'Everest',
          'Evos',
          'Excursion',
          'Expedition',
          'Explorer',
          'Explorer EV',
          'Explorer Sport Trac',
          'F150',
          'F250',
          'F350',
          'Fairlane',
          'Festiva',
          'Fiesta',
          'Flex',
          'Focus',
          'Focus RS',
          'Focus ST',
          'Freda',
          'Freestyle',
          'Fusion',
          'Galaxie',
          'Galaxy',
          'Granada',
          'Grand C-MAX',
          'GT',
          'Ixion',
          'Ka',
          'Kuga',
          'Laser',
          'LTD Crown Victoria',
          'Maverick',
          'Model T',
          'Mondeo',
          'Mondeo Sport',
          'Mustang',
          'Mustang Mach-E',
          'Orion',
          'Probe',
          'Puma',
          'Ranger',
          'S-MAX',
          'Scorpio',
          'Sierra',
          'Spectron',
          'SportKa',
          'StreetKa',
          'Taurus',
          'Telstar',
          'Tempo',
          'Territory',
          'Th!nk',
          'Thunderbird',
          'Torino',
          'Tourneo',
          'Tourneo Connect',
          'Tourneo Courier',
          'Tourneo Custom',
          'V8',
          'Windstar'],
 'Foton': ['Conqueror 3',
           'Conqueror 5',
           'Conqueror 7',
           'Conqueror Plus',
           'Mars 7',
           'Mars 9',
           'Midi',
           'Sauvana',
           'Tunland',
           'Tunland F9',
           'Tunland G7',
           'Tunland G9',
           'Tunland V7',
           'Tunland V9',
           'View'],
 'GAC': ['Aion Hyper GT',
         'Aion Hyper HL',
         'Aion Hyper HT',
         'Aion Hyper SSR',
         'Aion LX',
         'Aion LX Plus',
         'Aion S',
         'Aion S Plus',
         'Aion UT',
         'Aion V',
         'Aion V Plus',
         'Aion Y',
         'Aion Y Plus',
         'EA6',
         'Empow',
         'GN8',
         'GS4',
         'GS5',
         'GS8',
         'iA5',
         'S7',
         'Trumpchi',
         'Trumpchi E8',
         'Trumpchi E9',
         'Trumpchi Emkoo',
         'Trumpchi Empow',
         'Trumpchi ES9',
         'Trumpchi GA3',
         'Trumpchi GA3S',
         'Trumpchi GA4',
         'Trumpchi GA4 Plus',
         'Trumpchi GA5',
         'Trumpchi GA6',
         'Trumpchi GA8',
         'Trumpchi GE3',
         'Trumpchi GM6',
         'Trumpchi GM8',
         'GS3',
         'Trumpchi GS3 Power',
         'Trumpchi GS4',
         'Trumpchi GS4 Coupe',
         'Trumpchi GS4 Max',
         'Trumpchi GS4 Plus',
         'Trumpchi GS5',
         'Trumpchi GS5 Super',
         'Trumpchi GS7',
         'Trumpchi GS8',
         'Trumpchi GS8S',
         'Trumpchi M6',
         'Trumpchi M6 Pro',
         'M8',
         'Trumpchi S7',
         'Trumpchi S9',
         'Way'],
 'GMC': ['Acadia',
         'Canyon',
         'Envoy',
         'Hummer EV',
         'Jimmy',
         'GMC Savana',
         'Sierra',
         'Sierra EV',
         'Suburban',
         'Terrain',
         'Typhoon',
         'GMC Vandura',
         'Yukon'],
 'Geely': ['Atlas',
           'Atlas Pro',
           'Azkarra',
           'Binrui',
           'Binrui Cool',
           'Binyue',
           'Binyue Cool',
           'Binyue L',
           'Borui',
           'Borui GE',
           'Boyue',
           'Boyue Cool',
           'Boyue L',
           'Boyue Pro',
           'Boyue X',
           'Cityray',
           'CK Otaka',
           'Cowboy',
           'Emgrand EC7',
           'Emgrand EC8',
           'Emgrand GL',
           'Emgrand GT',
           'Emgrand',
           'Emgrand L',
           'Emgrand S',
           'EX5',
           'EX5 EM-i',
           'Emgrand X7',
           'Farizon FX',
           'Galaxy A7',
           'Galaxy E5',
           'Galaxy E8',
           'Galaxy L380',
           'Galaxy L6',
           'Galaxy L7',
           'Galaxy M9',
           'Galaxy Starshine 6',
           'Galaxy Starshine 8',
           'Galaxy Starship 7',
           'GC6',
           'Geometry A',
           'Geometry A Pro',
           'Geometry C',
           'Geometry E',
           'Geometry G6',
           'Geometry M6',
           'Geometry Panda Mini',
           'GS',
           'Haoyue',
           'Haoyue L',
           'Haoyue Pro',
           'ICON',
           'Jiyue Robo 01',
           'Jiaji',
           'Jiyue Robo 07',
           'LC Cross',
           'MK',
           'MK Cross',
           'Monjaro',
           'Okavango',
           'Preface',
           'SC7',
           'SL',
           'Coolray',
           'Tugella',
           'TX4',
           'Vision FC',
           'Vision S1',
           'Vision X1',
           'Vision X3',
           'Vision X3 Pro',
           'Vision X6',
           'Vision X6 Pro',
           'Geome Xingyuan',
           'Xingyue',
           'Xingyue L',
           'Xingyue S'],
 'Genesis': ['EQ900', 'G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'GV80 Coupe'],
 'Great Wall': ['Coolbear',
                'Cowry',
                'Florid',
                'Hover',
                'Hover H3',
                'Hover H5',
                'Hover H6',
                'Hover M2',
                'Hover M4',
                'Pao',
                'Peri',
                'Poer',
                'Poer KingKong',
                'Safe',
                'Sailor',
                'Shanhai Poer',
                'Sing',
                'Voleex c30',
                'Wingle',
                'Wingle 7'],
 'Haval': ['Big Dog DaGou',
           'Chitu',
           'Cool Dog KuGou',
           'Dargo',
           'F5',
           'F7',
           'F7x',
           'H1',
           'Great Wall H10',
           'H2',
           'H2s',
           'H3',
           'H4',
           'H4 Pro',
           'H5',
           'H6',
           'H6 Coupe',
           'H6L',
           'H6S',
           'H7',
           'H8',
           'H9',
           'H-Dog',
           'Jolion',
           'M6',
           'M6 Plus',
           'Raptor',
           'Shenshou',
           'Xiaolong',
           'Xiaolong Max'],
 'Honda': ['1300',
           '145',
           'Accord',
           'Accord Inspire',
           'Acty',
           'Airwave',
           'Ascot',
           'Ascot Innova',
           'Avancier',
           'Ballade',
           'Beat',
           'Breeze',
           'Capa',
           'City',
           'Civic',
           'Civic Ferio',
           'Civic Shuttle',
           'Civic Type R',
           'Concerto',
           'CR-V',
           'CR-X',
           'CR-X del Sol',
           'CR-Z',
           'Crider',
           'Crossroad',
           'Crosstour',
           'Domani',
           'e',
           'e:NP1',
           'e:NP2',
           'e:NS1',
           'e:NS2',
           'e:NY1',
           'Edix',
           'Element',
           'Elysion',
           'Envix',
           'Clarity',
           'Fit',
           'Fit Aria',
           'Fit Shuttle',
           'FR-V',
           'Freed',
           'Freed+',
           'Freed Spike',
           'Grace',
           'Horizon',
           'HR-V',
           'Insight',
           'Inspire',
           'Integra',
           'Integra SJ',
           'Jade',
           'Jazz',
           'Lagreat',
           'Legend',
           'Life',
           'Life Dunk',
           'Logo',
           'MDX',
           'M-NV',
           'Mobilio',
           'Mobilio Spike',
           'N-BOX',
           'N-BOX+',
           'N-ONE',
           'N-VAN',
           'N-WGN',
           'N-BOX Slash',
           'NSX',
           'Odyssey',
           'Orthia',
           'P7',
           'Partner',
           'Passport',
           'Pilot',
           'Prelude',
           'Prologue',
           'Quint',
           'Rafaga',
           'Ridgeline',
           'S-MX',
           'S2000',
           'S660',
           'S7',
           'Saber',
           'Shuttle',
           'Stepwgn',
           'Stream',
           'Street',
           'Super-ONE',
           'Today',
           'Torneo',
           'UR-V',
           'Vamos',
           'Vamos Hobio',
           'Everus VE-1',
           'Vezel',
           'Vigor',
           'WR-V',
           'X-NV',
           'XR-V',
           'Z',
           'Zest',
           'ZR-V'],
 'Hongqi': ['E-HS3',
            'E-HS9',
            'E-QM5',
            'EH7',
            'Guoya',
            'H5',
            'H6',
            'H7',
            'H9',
            'HQ9',
            'HS3',
            'HS5',
            'HS6',
            'HS7',
            'HS9',
            'L1',
            'L5 Guoli',
            'LS7',
            'Tiangong 05',
            'Tiangong 06',
            'Tiangong 08'],
 'Huanghai': ['Antelope', 'Landscape F1', 'N2', 'N3', 'N7', 'Plutus'],
 'Huazi': ['Omega'],
 'Hummer': ['H1', 'H2', 'H3'],
 'Hyundai': ['Accent',
             'Atos',
             'Avante',
             'Azera',
             'Bayon',
             'Casper',
             'Celesta',
             'Centennial',
             'Coupe',
             'Creta',
             'Custin',
             'Custo',
             'Elantra',
             'Elexio',
             'Encino',
             'Entourage',
             'Equus',
             'Galloper',
             'Genesis',
             'Getz',
             'Grace',
             'Grand Creta',
             'Grand Santa Fe',
             'Grandeur',
             'H1',
             'H100',
             'XG',
             'i10',
             'i20',
             'i20 Active',
             'i30',
             'i40',
             'Inster',
             'Ioniq',
             'Ioniq 3',
             'Ioniq 5',
             'Ioniq 6',
             'Ioniq 9',
             'ix25',
             'ix35',
             'ix55',
             'Kona',
             'Kona Electric',
             'Lafesta',
             'Lantra',
             'Lavita',
             'Matrix',
             'Maxcruze',
             'Mistra',
             'Mufasa',
             'Nexo',
             'NF',
             'Palisade',
             'Presto',
             'S Coupe',
             'Santa Cruz',
             'Santa Fe',
             'Santa Fe Classic',
             'Solaris',
             'Sonata',
             'Starex',
             'Stargazer',
             'Staria',
             'Terracan',
             'Tiburon',
             'Trajet',
             'Tucson',
             'Tuscani',
             'Veloster',
             'Venue',
             'Veracruz',
             'Verna'],
 'IVECO': ['Massif'],
 'Infiniti': ['ESQ',
              'EX25',
              'EX30d',
              'EX35',
              'EX37',
              'FX30d',
              'FX35',
              'FX37',
              'FX45',
              'FX50',
              'G20',
              'G25',
              'G35',
              'G37',
              'I30',
              'I35',
              'J30',
              'JX35',
              'M25',
              'M30',
              'M30d',
              'M35',
              'M35h',
              'M37',
              'M45',
              'M56',
              'Q30',
              'Q40',
              'Q45',
              'Q50',
              'Q60',
              'Q70',
              'QX30',
              'QX4',
              'QX50',
              'QX55',
              'QX56',
              'QX60',
              'QX65',
              'QX70',
              'QX80'],
 'Isuzu': ['117 Coupe',
           'Amigo',
           'Aska',
           'Axiom',
           'Bighorn',
           'Como',
           'D-MAX',
           'Fargo',
           'Fargo Filly',
           'Faster',
           'Filly',
           'Florian',
           'Gemini',
           'I-Mark',
           'Lingtuo',
           'Midi',
           'MU',
           'MU-X',
           'Pa Nero',
           'Piazza',
           'Piazza Nero',
           'Rodeo',
           'RE-MAX Ruimai',
           'T30 Explorer',
           'Trooper',
           'VehiCross',
           'Wizard'],
 'JAC': ['Binyue',
         'iEV4',
         'iEV5',
         'iEV6E',
         'iEV6E Sport',
         'iEV6S',
         'iEV7L',
         'iEV7S',
         'iEVA50',
         'iEVS4',
         'J2',
         'J3',
         'J5',
         'J6',
         'J7',
         'Jiayue A5',
         'JS2 Pro',
         'JS3',
         'JS4',
         'JS5',
         'JS6',
         'JS9',
         'M1',
         'Refine',
         'Refine A60',
         'Refine L6 Max',
         'Refine M3',
         'Refine M5',
         'Refine M6',
         'Refine R3',
         'Refine RF8',
         'Refine S2',
         'Refine S3',
         'Refine S4',
         'Refine S5',
         'Refine S7',
         'Rein',
         'RF8',
         'S1',
         'S3',
         'S3 Pro',
         'S5',
         'S7',
         'Sehol A5',
         'Sehol A5 Plus',
         'Sehol Aipao',
         'Sehol E10X',
         'Sehol E20X',
         'Sehol E40X',
         'Sehol QX',
         'Sehol X4',
         'Sehol X6',
         'Sehol X7',
         'Sehol X8',
         'Sehol X8 Plus',
         'T40',
         'T6',
         'T8',
         'T8 Pro',
         'T9',
         'Yttrium 3'],
 'JMC': ['Baodian', 'Dadao', 'Vigus', 'Yuhu 5', 'Yuhu 7', 'Yuhu 9'],
 'Jaecoo': ['J5', 'J6', 'J7', 'J8'],
 'Jaguar': ['240',
            '340',
            'E-Pace',
            'F-Pace',
            'F-Type',
            'I-Pace',
            'Mark I',
            'Mark II',
            'Mark IX',
            'S-type',
            'Sovereign',
            'X-Type',
            'XE',
            'XF',
            'XJS',
            'XJ',
            'XJ220',
            'XK'],
 'Jeep': ['Avenger',
          'Cherokee',
          'Commander',
          'Compass',
          'Gladiator',
          'Grand Cherokee',
          'Grand Commander',
          'Grand Wagoneer',
          'Liberty',
          'Patriot',
          'Renegade',
          'Wagoneer',
          'Wrangler'],
 'Jetour': ['Dashing',
            'F700',
            'G700',
            'G900',
            'L6',
            'L7',
            'L9',
            'T1',
            'T2',
            'Traveller',
            'X50',
            'X70',
            'X70 Coupe',
            'X70 Plus',
            'X70 Pro',
            'X70L',
            'X70M',
            'X70S',
            'X90',
            'X90 Plus',
            'X90 Pro',
            'X95'],
 'Jetta': ['VA3', 'VA7', 'VS5', 'VS7', 'VS8'],
 'KGM': ['Actyon',
         'Korando',
         'Musso',
         'Musso EV',
         'Musso Grand',
         'Musso Khan',
         'Musso Sports',
         'Rexton',
         'Rexton Sports',
         'Rexton Sports Khan',
         'Tivoli',
         'Torres',
         'Torres EVX',
         'XLV'],
 'Kaiyi': ['E5', 'X3', 'X3 Pro', 'X7 Kunlun'],
 'Kia': ['Avella',
         'Besta',
         'Bongo',
         'Borrego',
         'Cadenza',
         'Capital',
         'Carens',
         'Carnival',
         'Cerato',
         'Cerato Koup',
         'Clarus',
         'Credos',
         'EV3',
         'EV4',
         'EV5',
         'EV6',
         'EV9',
         'Forte',
         'K2',
         'K3',
         'K4',
         'K5',
         'K7',
         'K8',
         'K9',
         'K900',
         'KX1',
         'KX3',
         'KX5',
         'KX7',
         'KX Cross',
         'Lotze',
         'Magentis',
         'Mohave',
         'Morning',
         'Niro',
         'Opirus',
         'Optima',
         'Pegas',
         'Picanto',
         'Pregio',
         'Pride',
         'PV5',
         'Quoris',
         'Ray',
         'Retona',
         'Rio',
         'Rio X (X-Line)',
         'Rondo',
         'Sedona',
         'Seltos',
         'Sephia',
         'Shuma',
         'Soluto',
         'Sonet',
         'Sorento',
         'Soul',
         'Spectra',
         'Sportage',
         'Stinger',
         'Stonic',
         'Tasman',
         'Telluride',
         'Venga',
         'X-Trek',
         'Xceed'],
 'Knewstar': ['001'],
 'Lamborghini': ['Aventador',
                 'Countach',
                 'Diablo',
                 'Gallardo',
                 'Huracan',
                 'LM 002',
                 'Murcielago',
                 'Revuelto',
                 'Sian',
                 'Temerario',
                 'Urus'],
 'Lancia': ['Dedra', 'Delta', 'Thema'],
 'Land Rover': ['Defender',
                'Discovery',
                'Discovery Sport',
                'Freelander',
                'Range Rover',
                'Range Rover Evoque',
                'Range Rover Sport',
                'Range Rover Velar',
                'Series III'],
 'Lexus': ['CT200h',
           'ES200',
           'ES250',
           'ES260',
           'ES300',
           'ES300h',
           'ES330',
           'ES350',
           'ES350e',
           'ES350h',
           'ES500e',
           'GS200t',
           'GS250',
           'GS300',
           'GS300h',
           'GS350',
           'GS400',
           'GS430',
           'GS450h',
           'GS460',
           'GS F',
           'GX460',
           'GX470',
           'GX550',
           'GX550h',
           'HS250h',
           'IS200',
           'IS200d',
           'IS200t',
           'IS220d',
           'IS250',
           'IS250C',
           'IS300',
           'IS300C',
           'IS300h',
           'IS350',
           'IS350C',
           'IS500',
           'IS F',
           'LBX',
           'LC500',
           'LC500h',
           'LFA',
           'LM300h',
           'LM350',
           'LM350h',
           'LM500h',
           'LS350',
           'LS400',
           'LS430',
           'LS460',
           'LS460L',
           'LS500',
           'LS500h',
           'LS600h',
           'LS600hL',
           'LX450',
           'LX450d',
           'LX470',
           'LX500d',
           'LX570',
           'LX600',
           'LX700h',
           'NX200',
           'NX200t',
           'NX250',
           'NX260',
           'NX300',
           'NX300h',
           'NX350',
           'NX350h',
           'NX400h+',
           'NX450h+',
           'RC200t',
           'RC300',
           'RC300h',
           'RC350',
           'RC F',
           'RX200t',
           'RX270',
           'RX300',
           'RX330',
           'RX350',
           'RX350h',
           'RX350L',
           'RX400h',
           'RX450h',
           'RX450hL',
           'RX450h+',
           'RX500h',
           'RZ300e',
           'RZ350e',
           'RZ450e',
           'RZ500e',
           'RZ550e',
           'RZ600e',
           'SC300',
           'SC400',
           'SC430',
           'TX350',
           'TX500h',
           'TX550h+',
           'UX200',
           'UX250h',
           'UX260h',
           'UX300e',
           'UX300h'],
 'Li': ['i6', 'i8', 'L6', 'L7', 'L8', 'L9', 'Mega', 'ONE'],
 'Lifan': ['650 EV',
           'Breez',
           'Cebrium',
           'Celliya',
           'Foison',
           'Murman',
           'Myway',
           'Smily',
           'Solano',
           'X50',
           'X60',
           'X70',
           'X80'],
 'Lincoln': ['Aviator',
             'Blackwood',
             'Continental',
             'Corsair',
             'LS',
             'Mark LT',
             'MKC',
             'MKS',
             'MKT',
             'MKX',
             'MKZ',
             'Nautilus',
             'Navigator',
             'Town Car',
             'Zephyr'],
 'Livan': ['7', '9', 'S6 Pro', 'X3 Pro', 'X6 Pro'],
 'Lotus': ['2-Eleven',
           'Eletre',
           'Elise',
           'Emeya',
           'Emira',
           'Esprit',
           'Europa S',
           'Evora',
           'Exige',
           'For Me'],
 'Lynk & Co': ['01', '02', '03', '05', '06', '07', '08', '09', '10', '900', 'Z10', 'Z20'],
 'MG': ['3',
        '4 EV',
        '4X',
        '5',
        '5 Scorpio',
        '6',
        '6 Pro',
        '7',
        'Cyberster',
        'ES5',
        'EZS',
        'F',
        'HS',
        'MGB',
        'Mulan',
        'One',
        'Pilot',
        'Rui Teng',
        'RX5 Plus',
        'RX8',
        'RX9',
        'Sharp',
        'TF',
        'U9',
        'ZS'],
 'MINI': ['Aceman',
          'Cabrio',
          'Classic',
          'Clubman',
          'Countryman',
          'Coupe',
          'Crossover',
          'Hatch',
          'Paceman',
          'Roadster'],
 'Marussia': ['B1', 'B2'],
 'Maserati': ['3200 GT',
              'Coupe',
              'Ghibli',
              'GranCabrio',
              'GranSport',
              'GranTurismo',
              'Grecale',
              'Levante',
              'MC20',
              'Quattroporte',
              'Spyder'],
 'Maybach': ['57', '62'],
 'Mazda': ['121',
           '1500',
           '323',
           '323C',
           '323F',
           '616',
           '626',
           '818',
           '929',
           'Atenza',
           'Autozam AZ-1',
           'Autozam AZ-3',
           'Autozam Clef',
           'Axela',
           'AZ-Offroad',
           'AZ-Wagon',
           'B-Series',
           'Biante',
           'Bongo',
           'Bongo Brawny',
           'Bongo Friendee',
           'BT-50',
           'Capella',
           'Carol',
           'Chantez',
           'Cosmo',
           'Cronos',
           'CX-3',
           'CX-30',
           'CX-4',
           'CX-5',
           'CX-50',
           'CX-60',
           'CX-6e',
           'CX-7',
           'CX-70',
           'CX-8',
           'CX-80',
           'CX-9',
           'CX-90',
           'Demio',
           'Efini MPV',
           'Efini MS-6',
           'Efini MS-8',
           'Efini MS-9',
           'Efini RX-7',
           'Etude',
           'Eunos 100',
           'Eunos 300',
           'Eunos 500',
           'Eunos 800',
           'Eunos Cargo',
           'Eunos Cosmo',
           'Eunos Presso',
           'Eunos Roadster',
           'EZ-6',
           'EZ-60',
           'Familia',
           'Familia S-Wagon',
           'Flair',
           'Flair Crossover',
           'Flair Wagon',
           'Grand Familia',
           'Lantis',
           'Laputa',
           'Luce',
           'Mazda2',
           'Mazda3',
           'Mazda3 MPS',
           'Mazda5',
           'Mazda6',
           'Mazda6 MPS',
           'Mazda6e',
           'Mazda8',
           'Miata',
           'Millenia',
           'MPV',
           'MX-3',
           'MX-30',
           'MX-5',
           'MX-6',
           'Navajo',
           'Persona',
           'Premacy',
           'Proceed',
           'Proceed Levante',
           'Proceed Marvie',
           'Protege',
           'Revue',
           'Roadpacer',
           'Roadster',
           'RX-5',
           'RX-7',
           'RX-8',
           'Savanna',
           'Savanna RX-7',
           'Scrum',
           'Sentia',
           'Spiano',
           'Tribute',
           'Verisa',
           'Xedos 6',
           'Xedos 9'],
 'McLaren': ['520S', '540C', '570GT', '570S', '720S', '750S', 'Artura', 'GT', 'P1', 'W1'],
 'Mercedes-Benz': ['190',
                   'A-Class',
                   'AMG GT',
                   'AMG One',
                   'B-Class',
                   'C-Class',
                   'Citan',
                   'CL-Class',
                   'CLA-Class',
                   'CLC-Class',
                   'CLE-Class',
                   'CLK-Class',
                   'CLS-Class',
                   'E-Class',
                   'EQA',
                   'EQB',
                   'EQC',
                   'EQE',
                   'EQE SUV',
                   'EQS',
                   'EQS SUV',
                   'EQV',
                   'G-Class',
                   'GL-Class',
                   'GLA-Class',
                   'GLB-Class',
                   'GLC-Class',
                   'GLC Coupe',
                   'GLC EQ',
                   'GLE-Class',
                   'GLE Coupe',
                   'GLK-Class',
                   'GLS-Class',
                   'M-Class',
                   'Metris',
                   'R-Class',
                   'S-Class',
                   'SL-Class',
                   'SLC-Class',
                   'SLK-Class',
                   'SLR McLaren',
                   'SLS AMG',
                   'V-Class',
                   'Vaneo',
                   'Viano',
                   'Vito',
                   'VLE',
                   'W108',
                   'W111',
                   'W114',
                   'W115',
                   'W120',
                   'W121',
                   'W123',
                   'W128',
                   'W136',
                   'W142',
                   'W143',
                   'W180',
                   'W187',
                   'W189',
                   'W21',
                   'X-Class'],
 'Mitsubishi': ['3000GT',
                'Airtrek',
                'Aspire',
                'ASX',
                'Attrage',
                'Bravo',
                'Carisma',
                'Celeste',
                'Challenger',
                'Chariot',
                'Chariot Grandis',
                'Colt',
                'Colt Plus',
                'Cordia',
                'Debonair',
                'Delica',
                'Delica D:2',
                'Delica D:3',
                'Delica D:5',
                'Delica Mini',
                'Destinator',
                'Diamante',
                'Dignity',
                'Mirage Dingo',
                'Dion',
                'Eclipse',
                'Eclipse Cross',
                'eK Active',
                'eK classy',
                'ek Custom',
                'eK Sport',
                'eK Wagon',
                'eK Space',
                'eK X',
                'Emeraude',
                'Endeavor',
                'Eterna',
                'Expo',
                'Freeca',
                'FTO',
                'Galant',
                'Galant Fortis',
                'Grandis',
                'Grunder',
                'GTO',
                'i',
                'i-MiEV',
                'Jeep',
                'L200',
                'L300',
                'L400',
                'Lancer',
                'Lancer Cedia',
                'Lancer Evolution',
                'Lancer EX',
                'Lancer Fortis',
                'Legnum',
                'Libero',
                'Minica',
                'Minica Toppo',
                'Minicab',
                'Minicab MiEV',
                'Mirage',
                'Montero',
                'Montero Sport',
                'Outlander',
                'Outlander Sport',
                'Pajero',
                'Pajero iO',
                'Pajero Junior',
                'Pajero Mini',
                'Pajero Pinin',
                'Pajero Sport',
                'Pistachio',
                'Proudia',
                'Raider',
                'RVR',
                'Sapporo',
                'Savrin',
                'Sigma',
                'Space Gear',
                'Space Runner',
                'Space Star',
                'Space Wagon',
                'Starion',
                'Strada',
                'Toppo',
                'Toppo BJ',
                'Toppo BJ Wide',
                'Town Box',
                'Town Box Wide',
                'Tredia',
                'Triton',
                'Xforce',
                'Xpander',
                'Xpander Cross'],
 'Nissan': ['100NX',
            '180SX',
            '200SX',
            '240SX',
            '300ZX',
            '350Z',
            '370Z',
            'AD',
            'Almera',
            'Almera Classic',
            'Altima',
            'Ariya',
            'Armada',
            'Aura',
            'Auster',
            'Avenir',
            'Avenir Salut',
            'Bassara',
            'BE-1',
            'Bluebird',
            'Bluebird Maxima',
            'Bluebird Sylphy',
            'Caravan',
            'Caravan Elgrand',
            'Cedric',
            'Cedric Cima',
            'Cefiro',
            'Cherry',
            'Cima',
            'Clipper',
            'Crew',
            'Cube',
            'Cube Cubic',
            'Datsun',
            'DAYZ',
            'DAYZ Roox',
            'Dualis',
            'e-NV200',
            'Elgrand',
            'Exa',
            'Expert',
            'Fairlady Z',
            'Figaro',
            'Frontier',
            'Frontier Pro',
            'Fuga',
            'Gloria',
            'Gloria Cima',
            'GT-R',
            'Homy',
            'Homy Elgrand',
            'Hypermini',
            'Juke',
            'Kait',
            'Kicks',
            'Kix',
            'Lafesta',
            'Langley',
            'Lannia',
            'Largo',
            'Latio',
            'Laurel',
            'Laurel Spirit',
            'Leaf',
            'Leopard',
            'Liberta Villa',
            'Liberty',
            'Lucino',
            'Magnite',
            'March',
            'March Box',
            'Maxima',
            'Micra',
            'Micra C+C',
            'Mistral',
            'Moco',
            'Murano',
            'N6',
            'N7',
            'Navara',
            'Note',
            'NP300',
            'NV100 Clipper',
            'NV200',
            'NV300',
            'NV350 Caravan',
            'NX-Coupe',
            'NX8',
            'Otti',
            'Pao',
            'Pathfinder',
            'Patrol',
            'Pickup',
            'Pino',
            'Pixo',
            'Prairie',
            'Prairie Joy',
            'Presage',
            'Presea',
            'President',
            'Primastar',
            'Primera',
            'Primera Camino',
            'Pulsar',
            'Qashqai',
            'Qashqai+2',
            'Quest',
            'Rasheen',
            'Rogue',
            'Rogue Sport',
            'Roox',
            'S-Cargo',
            'Safari',
            'Sakura',
            'Sentra',
            'Serena',
            'Silvia',
            'Skyline',
            'Skyline Crossover',
            'Skyline GT-R',
            'Stagea',
            'Stanza',
            'Sunny',
            'Sunny California',
            'Sunny RZ-1',
            'Sylphy',
            'Teana',
            'Terra',
            'Terrano',
            'Terrano II',
            'Terrano Regulus',
            'Tiida',
            'Tiida Latio',
            'Tino',
            'Titan',
            'Urvan',
            'Vanette',
            'Vanette Serena',
            'Versa',
            'Versa Note',
            'Violet',
            'Volkswagen Santana',
            'Wingroad',
            'X-Trail',
            'Xterra',
            'Z'],
 'OMODA': ['C5', 'C7', 'S5', 'S5 GT'],
 'Opel': ['1200',
          '1900',
          'Adam',
          'Admiral',
          'Agila',
          'Ampera',
          'Antara',
          'Ascona',
          'Astra',
          'Astra Family',
          'Astra GTC',
          'Calibra',
          'Campo',
          'Cascada',
          'Combo',
          'Commodore',
          'Corsa',
          'Crossland',
          'Diplomat',
          'Frontera',
          'Grandland X',
          'GT',
          'Insignia',
          'Kadett',
          'Kapitan',
          'Karl',
          'Manta',
          'Meriva',
          'Mokka',
          'Monterey',
          'Monza',
          'Olympia',
          'Omega',
          'P4',
          'Rekord',
          'Rocks-e',
          'Senator',
          'Signum',
          'Sintra',
          'Speedster',
          'Super 6',
          'Tigra',
          'Vectra',
          'Vita',
          'Vivaro',
          'Zafira',
          'Zafira Life'],
 'Peugeot': ['1007',
             '104',
             '106',
             '107',
             '108',
             '2008',
             '201',
             '202',
             '203',
             '204',
             '205',
             '206',
             '207',
             '207i',
             '208',
             '3008',
             '301',
             '304',
             '305',
             '306',
             '307',
             '308',
             '309',
             '4007',
             '4008',
             '403',
             '404',
             '405',
             '406',
             '407',
             '408',
             '5008',
             '504',
             '505',
             '508',
             '604',
             '605',
             '607',
             '806',
             '807',
             'Bipper',
             'Expert',
             'Hoggar',
             'iOn',
             'Partner',
             'Partner Origin',
             'Partner Tepee',
             'RCZ',
             'Rifter',
             'Traveller'],
 'Plymouth': ['Barracuda', 'Breeze', 'Fury', 'Laser', 'Neon', 'Prowler', 'Voyager'],
 'Polestar': ['1', '2', '3', '4'],
 'Pontiac': ['6000',
             'Aztek',
             'Bonneville',
             'Fiero',
             'Firebird',
             'G6',
             'Grand Am',
             'Grand Prix',
             'GTO',
             'Lemans',
             'Montana',
             'Solstice',
             'Sunbird',
             'Sunfire',
             'Torrent',
             'Trans Sport',
             'Vibe',
             'Wave'],
 'Porsche': ['356',
             '911',
             '914',
             '918',
             '924',
             '928',
             '944',
             '968',
             'Boxster',
             'Carrera GT',
             'Cayenne',
             'Cayenne Coupe',
             'Cayman',
             'Macan',
             'Panamera',
             'Taycan'],
 'RAM': ['1500', '2500', '3500'],
 'Ravon': ['Gentra', 'Matiz', 'Nexia R3', 'R2', 'R4'],
 'Renault': ['11',
             '14',
             '18',
             '19',
             '21',
             '25',
             '4',
             '5 E-Tech',
             'Alaskan',
             'Arkana',
             'Austral',
             'Avantime',
             'Captur',
             'City K-ZE',
             'Clio',
             'Dokker',
             'Dokker Stepway',
             'Duster',
             'Espace',
             'Estafette',
             'Express',
             'Filante',
             'Fluence',
             'Fluence Z.E.',
             'Grand Koleos',
             'Grand Scenic',
             'Kadjar',
             'Kangoo',
             'Kangoo Z.E.',
             'Kaptur',
             'Koleos',
             'KWID',
             'Laguna',
             'Latitude',
             'Lodgy',
             'Logan',
             'Logan Stepway',
             'Lutecia',
             'Megane',
             'Modus',
             'QM6',
             'R5',
             'R9',
             'Rafale',
             'Safrane',
             'Sandero',
             'Sandero Stepway',
             'Scenic',
             'Scenic RX4',
             'Sport Spider',
             'Symbol',
             'Talisman',
             'Trafic',
             'Twingo',
             'Twizy',
             'Vel Satis',
             'Wind',
             'ZOE'],
 'Renault Samsung': ['QM3', 'QM5', 'QM6', 'SM3', 'SM3 Z.E.', 'SM5', 'SM6', 'SM7', 'XM3'],
 'Rolls-Royce': ['20/25',
                 'Corniche',
                 'Cullinan',
                 'Dawn',
                 'Flying Spur',
                 'Ghost',
                 'Park Ward',
                 'Phantom',
                 'Silver Cloud',
                 'Silver Seraph',
                 'Silver Spirit',
                 'Silver Spur',
                 'Spectre',
                 'Wraith'],
 'Rover': ['200', '25', '400', '45', '600', '75', '800', 'Streetwise'],
 'SEAT': ['131',
          '133',
          'Alhambra',
          'Altea',
          'Arona',
          'Arosa',
          'Cordoba',
          'Exeo',
          'Ibiza',
          'Inca',
          'Leon',
          'Tarraco',
          'Terra',
          'Toledo'],
 'SWM': ['G01',
         'G01 Pro',
         'G01F',
         'G01FF',
         'G03F',
         'G05',
         'G05 Pro',
         'Iron Man',
         'Tiger',
         'X2',
         'X3',
         'X7'],
 'Saab': ['9-2X',
          '9-3',
          '9-4X',
          '9-5',
          '9-7X',
          '90',
          '900',
          '9000',
          '92',
          '93',
          '95',
          '96',
          '99',
          'Sonett'],
 'Skoda': ['100',
           '1000/1100 MB',
           '105/120/125',
           '1101/1102',
           '1201',
           '1202',
           '1203',
           '440/445/450',
           'Citigo',
           'Elroq',
           'Enyaq iV',
           'Enyaq iV Coupe',
           'Fabia',
           'Favorit',
           'Felicia',
           'Forman',
           'Garde',
           'Kamiq',
           'Karoq',
           'Kodiaq',
           'Kodiaq GT',
           'Kushaq',
           'Octavia',
           'Popular',
           'Rapid',
           'Roomster',
           'Scala',
           'Superb',
           'Yeti'],
 'Smart': ['#1', '#3', '#5', 'City', 'Forfour', 'Fortwo', 'Roadster', 'Crossblade'],
 'Solaris': ['HC', 'HS', 'KRS', 'KRX'],
 'Sollers': ['Sollers SA6', 'SF1', 'SP7', 'ST6', 'ST8', 'ST9'],
 'SsangYong': ['Actyon',
               'Actyon Sports',
               'Chairman',
               'SsangYong Istana',
               'Kallista',
               'Korando',
               'Korando Family',
               'Korando Sports',
               'Korando Turismo',
               'Kyron',
               'Musso',
               'Musso Sports',
               'Nomad',
               'Rexton',
               'Rexton Sports',
               'Rexton Sports Khan',
               'Rodius',
               'Stavic',
               'Tivoli',
               'Torres'],
 'Subaru': ['Alcyone',
            'Ascent',
            'B9 Tribeca',
            'Baja',
            'Brat',
            'BRZ',
            'Chiffon',
            'Crosstrek',
            'Dex',
            'Dias Wagon',
            'Domingo',
            'Exiga',
            'Exiga Crossover 7',
            'Forester',
            'Getaway',
            'Impreza',
            'Impreza WRX',
            'Impreza WRX STI',
            'Impreza XV',
            'Justy',
            'Layback',
            'Legacy',
            'Legacy B4',
            'Legacy Lancaster',
            'Leone',
            'Levorg',
            'Lucra',
            'Outback',
            'Pleo',
            'Pleo Plus',
            'R1',
            'R2',
            'Rex',
            'Sambar',
            'Solterra',
            'Stella',
            'SVX',
            'Trailseeker',
            'Traviq',
            'Trezia',
            'Tribeca',
            'Uncharted',
            'Vivio',
            'XV'],
 'Suzuki': ['Across',
            'Aerio',
            'Alto',
            'Alto Lapin',
            'Baleno',
            'Cappuccino',
            'Cara',
            'Carry Van',
            'Cervo',
            'Ciaz',
            'Cultus',
            'e Every',
            'e Vitara',
            'Eeco',
            'Equator',
            'Ertiga',
            'Escudo',
            'Esteem',
            'Every',
            'Forenza',
            'Fronte',
            'Fronx',
            'Grand Escudo',
            'Grand Vitara',
            'Grand Vitara XL-7',
            'Hustler',
            'Ignis',
            'Jimny',
            'Jimny Sierra',
            'Jimny Wide',
            'Kei',
            'Kizashi',
            'Landy',
            'Liana',
            'Mighty Boy',
            'MR Wagon',
            'Palette',
            'Reno',
            'S-Cross',
            'S-Presso',
            'Samurai',
            'Sidekick',
            'Solio',
            'Spacia',
            'Splash',
            'Swace',
            'Swift',
            'Swift+',
            'SX4',
            'Twin',
            'Verona',
            'Vitara',
            'Wagon R',
            'Wagon R Plus',
            'Wagon R Smile',
            'Wagon R Solio',
            'Wagon R Wide',
            'Works',
            'X-90',
            'Xbee',
            'XL7'],
 'TENET': ['T4', 'T7', 'T8'],
 'Tank': ['300', '400', '500', '700'],
 'Tesla': ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster'],
 'Toyota': ['2000GT',
            '4Runner',
            'Allex',
            'Allion',
            'Alphard',
            'Altezza',
            'Aqua',
            'Aristo',
            'Aurion',
            'Auris',
            'Avalon',
            'Avanza',
            'Avensis',
            'Avensis Verso',
            'Aygo',
            'bB',
            'Belta',
            'Blade',
            'Blizzard',
            'Brevis',
            'bZ',
            'bZ3',
            'bZ3X',
            'bZ4X',
            'bZ4X Touring',
            'bZ5',
            'bZ7',
            'bZ Woodland',
            'C-HR',
            'C-HR+',
            'C+pod',
            'Caldina',
            'Cami',
            'Camry',
            'Camry Gracia',
            'Camry Prominent',
            'Carina',
            'Carina E',
            'Carina ED',
            'Carina II',
            'Cavalier',
            'Celica',
            'Celsior',
            'Century',
            'Chaser',
            'Classic',
            'Comfort',
            'COMS',
            'Corolla',
            'Corolla Altis',
            'Corolla Axio',
            'Corolla Ceres',
            'Corolla Cross',
            'Corolla Fielder',
            'Corolla FX',
            'Corolla II',
            'Corolla iM',
            'Corolla Levin',
            'Corolla Rumion',
            'Corolla Runx',
            'Corolla Spacio',
            'Corolla Verso',
            'Corona',
            'Corona Exiv',
            'Corona Premio',
            'Corona SF',
            'Corsa',
            'Cressida',
            'Cresta',
            'Crown',
            'Crown Kluger',
            'Crown Majesta',
            'Crown Signia',
            'Crown Vellfire',
            'Curren',
            'Cynos',
            'Duet',
            'Echo',
            'Esquire',
            'Estima',
            'Estima Emina',
            'Estima Lucida',
            'Etios',
            'Etios Cross',
            'FJ Cruiser',
            'Fortuner',
            'Frontlander',
            'Funcargo',
            'Gaia',
            'GR 86',
            'GR Corolla',
            'GR Yaris',
            'GranAce',
            'Grand Hiace',
            'Grand Highlander',
            'Granvia',
            'GT 86',
            'Harrier',
            'Hiace',
            'Hiace Regius',
            'Highlander',
            'Hilux Champ',
            'Hilux',
            'Hilux Surf',
            'Ipsum',
            'iQ',
            'Isis',
            'ist',
            'Izoa',
            'JPN TAXI',
            'Kluger V',
            'Land Cruiser',
            'Land Cruiser Cygnus',
            'Land Cruiser FJ',
            'Land Cruiser Prado',
            'Levin',
            'Lite Ace',
            'Lite Ace Noah',
            'Mark II',
            'Mark II Wagon Blit',
            'Mark II Wagon Qualis',
            'Mark X',
            'Mark X Zio',
            'Master Ace Surf',
            'Matrix',
            'Mega Cruiser',
            'Mirai',
            'Model F',
            'MR-S',
            'MR2',
            'Nadia',
            'Noah',
            'Opa',
            'Origin',
            'Paseo',
            'Passo',
            'Passo Sette',
            'Picnic',
            'Pixis Epoch',
            'Pixis Joy',
            'Pixis Mega',
            'Pixis Space',
            'Pixis Van',
            'Platz',
            'Porte',
            'Premio',
            'Previa',
            'Prius',
            'Prius Alpha',
            'Prius C',
            'Prius PHV',
            'Prius Plus',
            'Prius Prime',
            'Prius v',
            'Proace',
            'Proace City',
            'Proace Verso',
            'Probox',
            'Progres',
            'Pronard',
            'Publica',
            'Ractis',
            'Raize',
            'Raum',
            'RAV4',
            'Regius',
            'Regius Ace',
            'Reiz',
            'Roomy',
            'Rush',
            'Sai',
            'Scepter',
            'SD',
            'Sequoia',
            'Sera',
            'SF',
            'Sienna',
            'Sienta',
            'Soarer',
            'Solara',
            'Soluna',
            'Spade',
            'Sparky',
            'Sprinter',
            'Sprinter Carib',
            'Sprinter Marino',
            'Sprinter Trueno',
            'Starlet',
            'Succeed',
            'Supra',
            'T100',
            'Tacoma',
            'Tank',
            'Tercel',
            'Touring Hiace',
            'Town Ace',
            'Town Ace Noah',
            'Tundra',
            'Urban Cruiser',
            'Vanguard',
            'Vellfire',
            'Veloz',
            'Venza',
            'Verossa',
            'Verso',
            'Verso-S',
            'Vios',
            'Vista',
            'Vista Ardeo',
            'Vitz',
            'Voltz',
            'Voxy',
            'Wigo',
            'Wildlander',
            'WiLL Cypha',
            'WiLL Vi',
            'WiLL VS',
            'Windom',
            'Wish',
            'xA',
            'Yaris',
            'Yaris Ativ',
            'Yaris Cross',
            'Yaris iA',
            'Yaris L',
            'Yaris Verso'],
 'Vauxhall': ['Viva'],
 'Volkswagen': ['Amarok',
                'Arteon',
                'Atlas',
                'Atlas Cross Sport',
                'Beetle',
                'Bora',
                'C-Trek',
                'Caddy',
                'California',
                'Caravelle',
                'Corrado',
                'Golf Country',
                'Eos',
                'Fox',
                'Golf',
                'Golf Plus',
                'Golf Sportsvan',
                'ID.3',
                'ID.4',
                'ID.4 Crozz',
                'ID.4 X',
                'ID.5',
                'ID.6 Crozz',
                'ID.6 X',
                'ID.7',
                'ID.Unyx',
                'ID.Unyx 08',
                'ID.Buzz',
                'ID.Era 9X',
                'Jetta',
                'K70',
                'Kaefer',
                'Lamando',
                'Lamando L',
                'Lavida',
                'Lavida XR',
                'Lupo',
                'Magotan',
                'Multivan',
                'Passat',
                'Passat CC',
                'Passat Pro',
                'Phaeton',
                'Phideon',
                'Pointer',
                'Polo',
                'Rabbit',
                'Routan',
                'Sagitar',
                'Sagitar L',
                'Santana',
                'Saveiro',
                'Scirocco',
                'Sharan',
                'T-Cross',
                'T-Roc',
                'Tacqua',
                'Talagon',
                'Taos',
                'Tavendor',
                'Tayron',
                'Tayron L',
                'Tayron X',
                'Teramont',
                'Teramont Pro',
                'Teramont X',
                'Tharu',
                'Tharu XR',
                'Tiguan',
                'Tiguan Allspace',
                'Tiguan L',
                'Tiguan X',
                'Touareg',
                'Touran',
                'Touran L',
                'Transporter',
                'Type 2',
                'up!',
                'Vento',
                'Viloran',
                'XL1'],
 'Volvo': ['260',
           '340',
           '343',
           '345',
           '360',
           '440',
           '460',
           '480',
           '850',
           '960',
           'C30',
           'C40',
           'C70',
           'EM90',
           'ES90',
           'EX30',
           'EX40',
           'EX60',
           'EX90',
           'S40',
           'S60',
           'S70',
           'S80',
           'S90',
           'V40',
           'V50',
           'V60',
           'V70',
           'V90',
           'XC40',
           'XC60',
           'XC70',
           'XC90'],
 'Vortex': ['Corda', 'Estina', 'Tingo'],
 'Voyah': ['Courage',
           'Dream Plus',
           'Dream',
           'Free',
           'Free Plus',
           'Passion EVR',
           'Passion EV',
           'Passion L',
           'Taishan'],
 'Xiaomi': ['SU7', 'YU7'],
 'Zeekr': ['001', '007', '009', '7X', '8X', '9X', 'Mix', 'X'],
 'ГАЗ': ['12 ЗИМ',
         '18',
         '21 Волга',
         '22 Волга',
         '24 Волга',
         '31029 Волга',
         '3102 Волга',
         '3105 Волга',
         '31105 Волга',
         '3110 Волга',
         '3111 Волга',
         '67',
         '69',
         'Аврора',
         '13 Чайка',
         '14 Чайка',
         '2330 Тигр',
         'М-72',
         'М1',
         'Победа',
         'Соболь НН',
         'Трофим',
         'Волга Сайбер'],
 'Лада': ['2101',
          '2102',
          '2103',
          '2104',
          '2105',
          '2106',
          '2107',
          '2108',
          '2109',
          '21099',
          '2110',
          '2111',
          '2112',
          '2113 Самара',
          '2114 Самара',
          '2115 Самара',
          '2120 Надежда',
          '4x4 2121 Нива',
          '2129',
          '4x4 2131 Нива',
          'Нива Пикап',
          '4x4 Бронто',
          '4x4 Урбан',
          'Аура',
          'Азимут',
          'EL LADA',
          'Гранта',
          'Гранта Кросс',
          'Гранта Спорт',
          'Искра',
          'Искра Кросс',
          'Калина',
          'Калина Кросс',
          'Калина Спорт',
          'Ларгус',
          'Ларгус Кросс',
          'Нива (2020-21 гг.)',
          'Нива Бронто',
          'Нива Легенд',
          'Нива Спорт',
          'Нива Тревел',
          '1111 Ока',
          'Приора',
          'Рива',
          'Samara',
          'Тарзан',
          'Веста',
          'Веста Кросс',
          'Веста Спорт',
          'Х-Кросс 5',
          'Х-рей',
          'Х-рей Кросс'],
 'Москвич': ['2137',
             '2138',
             '2140',
             '2141',
             '2335',
             '3',
             '3е',
             '400',
             '401',
             '402',
             '403',
             '407',
             '408',
             '410',
             '411',
             '412',
             '426',
             '6',
             '8',
             'M70',
             'M90'],
 'ТагАЗ': ['Aquila', 'С10', 'С190', 'Роад Партнер', 'Тагер', 'Вега'],
 'УАЗ': ['3151',
         '3153',
         '3159',
         '3160',
         'Патриот Спорт',
         '469',
         'УАЗ Буханка',
         'Хантер',
         'Патриот',
         'Пикап',
         'Симбир']}


def upgrade() -> None:
    conn = op.get_bind()
    rows = conn.execute(
        text("SELECT id, name FROM app.vehicle_brands WHERE name = ANY(:names)"),
        {"names": list(MODELS_BY_BRAND.keys())},
    ).fetchall()
    brand_id_by_name = {name: bid for bid, name in rows}

    missing = set(MODELS_BY_BRAND) - set(brand_id_by_name)
    if missing:
        raise RuntimeError(
            f"Бренды не найдены в app.vehicle_brands: {sorted(missing)}"
        )

    for brand_name, models in MODELS_BY_BRAND.items():
        conn.execute(
            text(
                "INSERT INTO app.vehicle_models (brand_id, name) "
                "SELECT :b, m FROM unnest(CAST(:names AS text[])) AS t(m) "
                "ON CONFLICT (brand_id, name) DO NOTHING"
            ),
            {"b": brand_id_by_name[brand_name], "names": models},
        )


def downgrade() -> None:
    """Удаляет только модели, добавленные этой миграцией.

    Audi-модели вставлены миграцией 0004 — их не трогаем.
    """
    conn = op.get_bind()
    conn.execute(
        text(
            "DELETE FROM app.vehicle_models "
            "WHERE brand_id IN ("
            "  SELECT id FROM app.vehicle_brands "
            "  WHERE name = ANY(:names) AND name <> 'Audi'"
            ")"
        ),
        {"names": list(MODELS_BY_BRAND.keys())},
    )
