"""Initial migration

Revision ID: cc8be3474d98
Revises: 
Create Date: 2026-01-08 21:56:50.453517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8be3474d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('position', sa.Enum('admin', 'manager', 'mechanic', name='employeeposition'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('salary_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)

    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.Enum('yookassa', 'sms', 'email', 'parts_supplier', 'gibdd', name='integrationtype'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_logs_id'), ['id'], unique=False)

    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('engine', 'transmission', 'suspension', 'brakes', 'electrical', 'body', 'consumables', 'other', name='partcategory'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_part_number'), ['part_number'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('owner_phone', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vin'), ['vin'], unique=True)

    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('diagnostics', 'repair', 'maintenance', 'body_work', 'painting', 'other', name='workcategory'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_works_id'), ['id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new', 'estimation', 'in_progress', 'ready_for_payment', 'paid', 'completed', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['mechanic_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_number'), ['number'], unique=True)

    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'calculated', 'paid', name='salarystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salaries_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'mechanic', 'accountant', name='userrole'), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('warehouse_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id')
    )
    with op.batch_alter_table('warehouse_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_items_id'), ['id'], unique=False)

    op.create_table('order_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_parts_id'), ['id'], unique=False)

    op.create_table('order_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_works_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'YOOKASSA', name='paymentmethod'), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_yookassa_payment_id'), ['yookassa_payment_id'], unique=True)

    op.create_table('warehouse_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('incoming', 'outgoing', 'adjustment', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_item_id'], ['warehouse_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_transactions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_transactions_id'))

    op.drop_table('warehouse_transactions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_yookassa_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('order_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_works_id'))

    op.drop_table('order_works')
    with op.batch_alter_table('order_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_parts_id'))

    op.drop_table('order_parts')
    with op.batch_alter_table('warehouse_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_items_id'))

    op.drop_table('warehouse_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salaries_id'))

    op.drop_table('salaries')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_number'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))

    op.drop_table('orders')
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_id'))

    op.drop_table('works')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vin'))
        batch_op.drop_index(batch_op.f('ix_vehicles_license_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parts_part_number'))
        batch_op.drop_index(batch_op.f('ix_parts_id'))

    op.drop_table('parts')
    with op.batch_alter_table('integration_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_logs_id'))

    op.drop_table('integration_logs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###

